name: Trigger auto deployment for minggu-container-apps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/minggu-container-apps-AutoDeployTrigger-6fd5a75b-f79e-4c79-9e8b-1bc086127f57.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MINGGUCONTAINERAPPS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MINGGUCONTAINERAPPS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MINGGUCONTAINERAPPS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.MINGGUCONTAINERAPPS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MINGGUCONTAINERAPPS_REGISTRY_PASSWORD }}
          containerAppName: minggu-container-apps
          resourceGroup: minggu-VM
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


